import mongoose, { Schema, Document as MongooseDocument } from 'mongoose';

export interface IProjectIdea extends MongooseDocument {
  title: string;
  description: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  careerPaths: string[];
  technologies: string[];
  estimatedTime: string;
  features: string[];
  isAIGenerated: boolean;
  userId?: mongoose.Types.ObjectId; // If generated by/for a specific user
}

const ProjectIdeaSchema = new Schema<IProjectIdea>({
  title: { type: String, required: true },
  description: { type: String, required: true },
  difficulty: { type: String, enum: ['beginner', 'intermediate', 'advanced'], required: true },
  careerPaths: [{ type: String }],
  technologies: [{ type: String }],
  estimatedTime: { type: String, required: true },
  features: [{ type: String }],
  isAIGenerated: { type: Boolean, default: false },
  userId: { type: Schema.Types.ObjectId, ref: 'User' }
}, { timestamps: true });

export default mongoose.models.ProjectIdea || mongoose.model<IProjectIdea>('ProjectIdea', ProjectIdeaSchema);
